# ベースイメージの設定
FROM python:3.12

# 環境変数を設定 (key=value 形式を使用)
ENV PYTHON_ENV=PROD

# 作業ディレクトリを設定
WORKDIR /workspace

# 依存関係のインストール
COPY docker/prod/requirements.txt .
RUN apt -y update
RUN pip install -U pip
RUN pip3 install -r requirements.txt

# アプリケーションのソースコードをコピー
COPY backend/src/ ./src/

# アプリケーションの起動（.envはdocker-compose.prod.ymlのenv_fileで注入する）
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
