"""add deleted column to orders

Revision ID: 038061b49cf7
Revises: ad356875c961
Create Date: 2024-09-29 11:51:58.868436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038061b49cf7'
down_revision: Union[str, None] = 'ad356875c961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'deleted')
    # ### end Alembic commands ###
