"""empty message

Revision ID: 072f57b709f8
Revises: 45364f9142dd
Create Date: 2024-11-15 05:18:12.443803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '072f57b709f8'
down_revision: Union[str, None] = '45364f9142dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'colors')
    op.drop_column('items', 'infos')
    op.drop_column('items', 'model_name')
    op.drop_column('orders', 'capacity')
    op.drop_column('orders', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('color', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('orders', sa.Column('capacity', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('items', sa.Column('model_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('items', sa.Column('infos', mysql.JSON(), nullable=True))
    op.add_column('items', sa.Column('colors', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
