"""Added columns.

Revision ID: 1f08634c3709
Revises: 2d658913713f
Create Date: 2024-08-11 03:57:13.549812
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1f08634c3709'
down_revision: Union[str, None] = '2d658913713f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tmp_colors', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('tmp_model_name', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('tmp_infos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tmp_model_infos')
    op.drop_column('items', 'tmp_model_name')
    op.drop_column('items', 'tmp_colors')
    # ### end Alembic commands ###
