"""change column name

Revision ID: 2feb8f176509
Revises: 46c7af61227e
Create Date: 2024-09-17 07:34:14.056065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2feb8f176509'
down_revision: Union[str, None] = '46c7af61227e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('card_name', sa.String(length=255), nullable=True),
    sa.Column('closing_date', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.String(length=255), nullable=True),
    sa.Column('order_number', sa.String(length=11), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('repayment_amount', sa.Float(), nullable=True),
    sa.Column('arrival_date', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_card_name'), 'orders', ['card_name'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoicing', sa.String(length=50), nullable=False),
    sa.Column('last_name_kanji', sa.String(length=100), nullable=False),
    sa.Column('first_name_kanji', sa.String(length=100), nullable=False),
    sa.Column('last_name_kana', sa.String(length=100), nullable=False),
    sa.Column('first_name_kana', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.Column('other_job', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('prefecture', sa.String(length=50), nullable=False),
    sa.Column('city_address', sa.String(length=255), nullable=False),
    sa.Column('detailed_address', sa.String(length=255), nullable=True),
    sa.Column('agree', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=10), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_holder', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('items', sa.Column('colors', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('model_name', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('infos', sa.JSON(), nullable=True))
    op.drop_column('items', 'tmp_model_name')
    op.drop_column('items', 'tmp_infos')
    op.drop_column('items', 'tmp_colors')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tmp_colors', mysql.JSON(), nullable=True))
    op.add_column('items', sa.Column('tmp_infos', mysql.JSON(), nullable=True))
    op.add_column('items', sa.Column('tmp_model_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('items', 'infos')
    op.drop_column('items', 'model_name')
    op.drop_column('items', 'colors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_card_name'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
