"""add contract

Revision ID: 45364f9142dd
Revises: f33708bb9917
Create Date: 2024-11-12 04:19:06.822509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45364f9142dd'
down_revision: Union[str, None] = 'f33708bb9917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contract_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'contract_at')
    # ### end Alembic commands ###
