"""change columns

Revision ID: 46c7af61227e
Revises: eb34a7c5203c
Create Date: 2024-09-17 07:15:13.725223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46c7af61227e'
down_revision: Union[str, None] = 'eb34a7c5203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_orders_card_name', table_name='orders')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_orders_name', table_name='orders')
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.drop_table('orders')
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_index('ix_categories_id', table_name='categories')
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('items', 'image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'newPrice',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index('ix_items_id', table_name='items')
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.alter_column('items', 'newPrice',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('items', 'category_id')
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('card_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('closing_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('payment_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('order_number', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('device', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('capacity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('unit_price', mysql.FLOAT(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('repayment_amount', mysql.FLOAT(), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('arrival_date', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=True)
    op.create_index('ix_orders_name', 'orders', ['name'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('ix_orders_card_name', 'orders', ['card_name'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoicing', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name_kanji', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name_kanji', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name_kana', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name_kana', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('job', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('other_job', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('prefecture', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('detailed_address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('agree', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('branch_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('account_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('account_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('account_holder', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
