"""Added columns.

Revision ID: 62e5cbd53e01
Revises: b67e23455d45
Create Date: 2024-08-15 01:55:54.691307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62e5cbd53e01'
down_revision: Union[str, None] = 'b67e23455d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('arrival_date', sa.String(length=255), nullable=False))
    op.alter_column('orders', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'card_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'closing_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'payment_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'order_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=11),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'device',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'capacity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'detailed_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'detailed_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               nullable=False)
    op.alter_column('orders', 'note',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=500),
               existing_nullable=True)
    op.alter_column('orders', 'color',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'capacity',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'device',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'payment_date',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'closing_date',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'card_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.alter_column('orders', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               existing_nullable=True)
    op.drop_column('orders', 'arrival_date')
    # ### end Alembic commands ###
