"""empty message

Revision ID: 98310fc7953b
Revises: 529078734613
Create Date: 2024-11-01 02:18:59.927026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98310fc7953b'
down_revision: Union[str, None] = '529078734613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invoicing_number', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invoicing_number')
    # ### end Alembic commands ###
