"""order update

Revision ID: ad356875c961
Revises: 2feb8f176509
Create Date: 2024-09-19 12:40:44.672576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad356875c961'
down_revision: Union[str, None] = '2feb8f176509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('orders', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'card_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'order_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('orders', 'device',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'capacity',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'color',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'color',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'capacity',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'device',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'order_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('orders', 'card_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'item_id')
    # ### end Alembic commands ###
