"""Added columns.

Revision ID: b67e23455d45
Revises: 1f08634c3709
Create Date: 2024-08-11 05:59:53.956993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67e23455d45'
down_revision: Union[str, None] = '1f08634c3709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('card_name', sa.String(length=50), nullable=True),
    sa.Column('closing_date', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.String(length=50), nullable=True),
    sa.Column('order_number', sa.String(length=11), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('repayment_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_card_name'), 'orders', ['card_name'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_card_name'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
